// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HostAction = { requestId: string, action: string, payload?: unknown, };

export type HostActionResult = { requestId: string, success: boolean, payload?: unknown, error?: string, };

export type HostCapability = "media" | "volume" | "discord" | "systemStats" | "macros" | "appLaunch";

export type HostHello = { protocolVersion: number, hostName: string, capabilities: Array<HostCapability>, };

export type HostMessage = { "type": "host.hello" } & HostHello | { "type": "host.status" } & HostStatus | { "type": "host.action" } & HostAction | { "type": "host.actionResult" } & HostActionResult | { "type": "Unknown" };

export type HostStatus = { connected: boolean, };
